repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.14"
    hooks:
      - id: ruff
        language_version: python3
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [-vv]
        pass_filenames: false