name: Publish docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish-docs:
    name: Build and publish docs
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.PAGES_TOKEN }}

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pipenv"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: |
          pipenv sync --dev
          pipenv run pip install -e .

      - name: Update dataset files
        run: |
          pipenv run dataset-docs

      - name: Build docs
        run: |
          pipenv run mkdocs build

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: docs
          folder: site
