# .github/workflows/app.yaml
name: PyTest
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "tests/**"
      - "src/**"
      - "Pipfile"
      - "Pipfile.lock"
      - ".github/workflows/pytest.yml"

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Setup Python (faster than using Python container)
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pipenv"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
      - name: Run test suite
        run: |
          pipenv run tests -v
