name: PyTest
on:
  pull_request:
    paths:
      - "tests/**"
      - "src/**"
      - "Pipfile"
      - "Pipfile.lock"
      - .github/workflows/pytest.yml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Setup Python (faster than using Python container)
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pipenv"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Run test suite
        run: |
          pipenv run test -v
